# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Show_TDR.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Show_TDR(object):
    def setupUi(self, Show_TDR):
        Show_TDR.setObjectName("Show_TDR")
        Show_TDR.resize(1045, 890)
        self.centralwidget = QtWidgets.QWidget(Show_TDR)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1008, 900))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(800, 900))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_ans_experiment_result_code = QtWidgets.QLabel(self.widget)
        self.label_ans_experiment_result_code.setObjectName("label_ans_experiment_result_code")
        self.gridLayout_3.addWidget(self.label_ans_experiment_result_code, 23, 2, 1, 1)
        self.label_fw_ans_rst_code = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_fw_ans_rst_code.setFont(font)
        self.label_fw_ans_rst_code.setObjectName("label_fw_ans_rst_code")
        self.gridLayout_3.addWidget(self.label_fw_ans_rst_code, 25, 2, 1, 1)
        self.label_ans_result_code = QtWidgets.QLabel(self.widget)
        self.label_ans_result_code.setObjectName("label_ans_result_code")
        self.gridLayout_3.addWidget(self.label_ans_result_code, 22, 2, 1, 1)
        self.lineEdit_50_ans_flag = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_50_ans_flag.setObjectName("lineEdit_50_ans_flag")
        self.gridLayout_3.addWidget(self.lineEdit_50_ans_flag, 19, 3, 1, 1)
        self.label_ans_flag = QtWidgets.QLabel(self.widget)
        self.label_ans_flag.setObjectName("label_ans_flag")
        self.gridLayout_3.addWidget(self.label_ans_flag, 19, 2, 1, 1)
        self.lineEdit_21_request_dest_edge_proxy_IP = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_21_request_dest_edge_proxy_IP.setObjectName("lineEdit_21_request_dest_edge_proxy_IP")
        self.gridLayout_3.addWidget(self.lineEdit_21_request_dest_edge_proxy_IP, 20, 1, 1, 1)
        self.lineEdit_24_appl_id = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_24_appl_id.setObjectName("lineEdit_24_appl_id")
        self.gridLayout_3.addWidget(self.lineEdit_24_appl_id, 23, 1, 1, 1)
        self.label_dest_host = QtWidgets.QLabel(self.widget)
        self.label_dest_host.setObjectName("label_dest_host")
        self.gridLayout_3.addWidget(self.label_dest_host, 28, 0, 1, 1)
        self.lineEdit_20_request_source_edge_proxy_IP = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_20_request_source_edge_proxy_IP.setObjectName("lineEdit_20_request_source_edge_proxy_IP")
        self.gridLayout_3.addWidget(self.lineEdit_20_request_source_edge_proxy_IP, 19, 1, 1, 1)
        self.label_request_send_date = QtWidgets.QLabel(self.widget)
        self.label_request_send_date.setObjectName("label_request_send_date")
        self.gridLayout_3.addWidget(self.label_request_send_date, 8, 0, 1, 1)
        self.lineEdit_38_vplmn_id = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_38_vplmn_id.setObjectName("lineEdit_38_vplmn_id")
        self.gridLayout_3.addWidget(self.lineEdit_38_vplmn_id, 7, 3, 1, 1)
        self.label_reason_id = QtWidgets.QLabel(self.widget)
        self.label_reason_id.setObjectName("label_reason_id")
        self.gridLayout_3.addWidget(self.label_reason_id, 29, 2, 1, 1)
        self.lineEdit_25_cmd_code = QtWidgets.QLineEdit(self.widget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.lineEdit_25_cmd_code.setPalette(palette)
        self.lineEdit_25_cmd_code.setObjectName("lineEdit_25_cmd_code")
        self.gridLayout_3.addWidget(self.lineEdit_25_cmd_code, 24, 1, 1, 1)
        self.lineEdit_52_ans_rules_hit = QtWidgets.QLineEdit(self.widget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.lineEdit_52_ans_rules_hit.setPalette(palette)
        self.lineEdit_52_ans_rules_hit.setObjectName("lineEdit_52_ans_rules_hit")
        self.gridLayout_3.addWidget(self.lineEdit_52_ans_rules_hit, 21, 3, 1, 1)
        self.lineEdit_54_ans_experiment_result_code = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_54_ans_experiment_result_code.setObjectName("lineEdit_54_ans_experiment_result_code")
        self.gridLayout_3.addWidget(self.lineEdit_54_ans_experiment_result_code, 23, 3, 1, 1)
        self.label_ans_payload = QtWidgets.QLabel(self.widget)
        self.label_ans_payload.setObjectName("label_ans_payload")
        self.gridLayout_3.addWidget(self.label_ans_payload, 20, 2, 1, 1)
        self.label_session_id = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_session_id.setFont(font)
        self.label_session_id.setObjectName("label_session_id")
        self.gridLayout_3.addWidget(self.label_session_id, 22, 0, 1, 1)
        self.lineEdit_51_ans_payload = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_51_ans_payload.setObjectName("lineEdit_51_ans_payload")
        self.gridLayout_3.addWidget(self.lineEdit_51_ans_payload, 20, 3, 1, 1)
        self.label_request_source_edge_proxy_IP = QtWidgets.QLabel(self.widget)
        self.label_request_source_edge_proxy_IP.setObjectName("label_request_source_edge_proxy_IP")
        self.gridLayout_3.addWidget(self.label_request_source_edge_proxy_IP, 19, 0, 1, 1)
        self.lineEdit_56_fw_ans_rst_code = QtWidgets.QLineEdit(self.widget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.lineEdit_56_fw_ans_rst_code.setPalette(palette)
        self.lineEdit_56_fw_ans_rst_code.setObjectName("lineEdit_56_fw_ans_rst_code")
        self.gridLayout_3.addWidget(self.lineEdit_56_fw_ans_rst_code, 25, 3, 1, 1)
        self.lineEdit_55_fw_ans_payload = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_55_fw_ans_payload.setObjectName("lineEdit_55_fw_ans_payload")
        self.gridLayout_3.addWidget(self.lineEdit_55_fw_ans_payload, 24, 3, 1, 1)
        self.lineEdit_23_session_id = QtWidgets.QLineEdit(self.widget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.lineEdit_23_session_id.setPalette(palette)
        self.lineEdit_23_session_id.setObjectName("lineEdit_23_session_id")
        self.gridLayout_3.addWidget(self.lineEdit_23_session_id, 22, 1, 1, 1)
        self.label_dest_operator = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_dest_operator.setFont(font)
        self.label_dest_operator.setObjectName("label_dest_operator")
        self.gridLayout_3.addWidget(self.label_dest_operator, 0, 2, 1, 1)
        self.label_cmd_code = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_cmd_code.setFont(font)
        self.label_cmd_code.setObjectName("label_cmd_code")
        self.gridLayout_3.addWidget(self.label_cmd_code, 24, 0, 1, 1)
        self.label_request_dest_edge_proxy_IP = QtWidgets.QLabel(self.widget)
        self.label_request_dest_edge_proxy_IP.setObjectName("label_request_dest_edge_proxy_IP")
        self.gridLayout_3.addWidget(self.label_request_dest_edge_proxy_IP, 20, 0, 1, 1)
        self.label_ans_rules_hit = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_ans_rules_hit.setFont(font)
        self.label_ans_rules_hit.setObjectName("label_ans_rules_hit")
        self.gridLayout_3.addWidget(self.label_ans_rules_hit, 21, 2, 1, 1)
        self.label_appl_id = QtWidgets.QLabel(self.widget)
        self.label_appl_id.setObjectName("label_appl_id")
        self.gridLayout_3.addWidget(self.label_appl_id, 23, 0, 1, 1)
        self.label_resent = QtWidgets.QLabel(self.widget)
        self.label_resent.setObjectName("label_resent")
        self.gridLayout_3.addWidget(self.label_resent, 21, 0, 1, 1)
        self.lineEdit_34_req_hbh_id = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_34_req_hbh_id.setObjectName("lineEdit_34_req_hbh_id")
        self.gridLayout_3.addWidget(self.lineEdit_34_req_hbh_id, 3, 3, 1, 1)
        self.lineEdit_26_origin_host = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_26_origin_host.setObjectName("lineEdit_26_origin_host")
        self.gridLayout_3.addWidget(self.lineEdit_26_origin_host, 25, 1, 1, 1)
        self.label_reason = QtWidgets.QLabel(self.widget)
        self.label_reason.setObjectName("label_reason")
        self.gridLayout_3.addWidget(self.label_reason, 28, 2, 1, 1)
        self.lineEdit_53_ans_result_code = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_53_ans_result_code.setObjectName("lineEdit_53_ans_result_code")
        self.gridLayout_3.addWidget(self.lineEdit_53_ans_result_code, 22, 3, 1, 1)
        self.label_origin_host = QtWidgets.QLabel(self.widget)
        self.label_origin_host.setObjectName("label_origin_host")
        self.gridLayout_3.addWidget(self.label_origin_host, 25, 0, 1, 1)
        self.lineEdit_22_resent = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_22_resent.setObjectName("lineEdit_22_resent")
        self.gridLayout_3.addWidget(self.lineEdit_22_resent, 21, 1, 1, 1)
        self.label_fw_ans_payload = QtWidgets.QLabel(self.widget)
        self.label_fw_ans_payload.setObjectName("label_fw_ans_payload")
        self.gridLayout_3.addWidget(self.label_fw_ans_payload, 24, 2, 1, 1)
        self.label_fw_ans_exp_rst_code = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_fw_ans_exp_rst_code.setFont(font)
        self.label_fw_ans_exp_rst_code.setObjectName("label_fw_ans_exp_rst_code")
        self.gridLayout_3.addWidget(self.label_fw_ans_exp_rst_code, 26, 2, 1, 1)
        self.lineEdit_28_origin_Operator = QtWidgets.QLineEdit(self.widget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.lineEdit_28_origin_Operator.setPalette(palette)
        self.lineEdit_28_origin_Operator.setObjectName("lineEdit_28_origin_Operator")
        self.gridLayout_3.addWidget(self.lineEdit_28_origin_Operator, 27, 1, 1, 1)
        self.lineEdit_30_dest_realm = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_30_dest_realm.setObjectName("lineEdit_30_dest_realm")
        self.gridLayout_3.addWidget(self.lineEdit_30_dest_realm, 29, 1, 1, 1)
        self.lineEdit_58_fw_ans_err_msg = QtWidgets.QLineEdit(self.widget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.lineEdit_58_fw_ans_err_msg.setPalette(palette)
        self.lineEdit_58_fw_ans_err_msg.setObjectName("lineEdit_58_fw_ans_err_msg")
        self.gridLayout_3.addWidget(self.lineEdit_58_fw_ans_err_msg, 27, 3, 1, 1)
        self.label_request_send_time = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_request_send_time.setFont(font)
        self.label_request_send_time.setObjectName("label_request_send_time")
        self.gridLayout_3.addWidget(self.label_request_send_time, 9, 0, 1, 1)
        self.label_local_action = QtWidgets.QLabel(self.widget)
        self.label_local_action.setObjectName("label_local_action")
        self.gridLayout_3.addWidget(self.label_local_action, 9, 2, 1, 1)
        self.lineEdit_10_request_send_time = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_10_request_send_time.sizePolicy().hasHeightForWidth())
        self.lineEdit_10_request_send_time.setSizePolicy(sizePolicy)
        self.lineEdit_10_request_send_time.setMinimumSize(QtCore.QSize(0, 2))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.lineEdit_10_request_send_time.setPalette(palette)
        self.lineEdit_10_request_send_time.setObjectName("lineEdit_10_request_send_time")
        self.gridLayout_3.addWidget(self.lineEdit_10_request_send_time, 9, 1, 1, 1)
        self.lineEdit_39_req_rules_hit = QtWidgets.QLineEdit(self.widget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.lineEdit_39_req_rules_hit.setPalette(palette)
        font = QtGui.QFont()
        font.setItalic(False)
        self.lineEdit_39_req_rules_hit.setFont(font)
        self.lineEdit_39_req_rules_hit.setObjectName("lineEdit_39_req_rules_hit")
        self.gridLayout_3.addWidget(self.lineEdit_39_req_rules_hit, 8, 3, 1, 1)
        self.lineEdit_41_fw_ete_id = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_41_fw_ete_id.setObjectName("lineEdit_41_fw_ete_id")
        self.gridLayout_3.addWidget(self.lineEdit_41_fw_ete_id, 10, 3, 1, 1)
        self.lineEdit_11_answer_rcv_date = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_11_answer_rcv_date.setObjectName("lineEdit_11_answer_rcv_date")
        self.gridLayout_3.addWidget(self.lineEdit_11_answer_rcv_date, 10, 1, 1, 1)
        self.label_answer_rcv_date = QtWidgets.QLabel(self.widget)
        self.label_answer_rcv_date.setObjectName("label_answer_rcv_date")
        self.gridLayout_3.addWidget(self.label_answer_rcv_date, 10, 0, 1, 1)
        self.lineEdit_27_origin_realm = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_27_origin_realm.setObjectName("lineEdit_27_origin_realm")
        self.gridLayout_3.addWidget(self.lineEdit_27_origin_realm, 26, 1, 1, 1)
        self.lineEdit_29_dest_host = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_29_dest_host.setObjectName("lineEdit_29_dest_host")
        self.gridLayout_3.addWidget(self.lineEdit_29_dest_host, 28, 1, 1, 1)
        self.label_fw_ans_err_msg = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_fw_ans_err_msg.setFont(font)
        self.label_fw_ans_err_msg.setObjectName("label_fw_ans_err_msg")
        self.gridLayout_3.addWidget(self.label_fw_ans_err_msg, 27, 2, 1, 1)
        self.label_origin_realm = QtWidgets.QLabel(self.widget)
        self.label_origin_realm.setObjectName("label_origin_realm")
        self.gridLayout_3.addWidget(self.label_origin_realm, 26, 0, 1, 1)
        self.label_origin_Operator = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_origin_Operator.setFont(font)
        self.label_origin_Operator.setObjectName("label_origin_Operator")
        self.gridLayout_3.addWidget(self.label_origin_Operator, 27, 0, 1, 1)
        self.lineEdit_44_reroute = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_44_reroute.setObjectName("lineEdit_44_reroute")
        self.gridLayout_3.addWidget(self.lineEdit_44_reroute, 13, 3, 1, 1)
        self.label_dest_realm = QtWidgets.QLabel(self.widget)
        self.label_dest_realm.setObjectName("label_dest_realm")
        self.gridLayout_3.addWidget(self.label_dest_realm, 29, 0, 1, 1)
        self.label_answer_rcv_time = QtWidgets.QLabel(self.widget)
        self.label_answer_rcv_time.setObjectName("label_answer_rcv_time")
        self.gridLayout_3.addWidget(self.label_answer_rcv_time, 11, 0, 1, 1)
        self.lineEdit_12_answer_rcv_time = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_12_answer_rcv_time.setObjectName("lineEdit_12_answer_rcv_time")
        self.gridLayout_3.addWidget(self.lineEdit_12_answer_rcv_time, 11, 1, 1, 1)
        self.label_answer_send_date = QtWidgets.QLabel(self.widget)
        self.label_answer_send_date.setObjectName("label_answer_send_date")
        self.gridLayout_3.addWidget(self.label_answer_send_date, 14, 0, 1, 1)
        self.lineEdit_42_fw_hbh_id = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_42_fw_hbh_id.setObjectName("lineEdit_42_fw_hbh_id")
        self.gridLayout_3.addWidget(self.lineEdit_42_fw_hbh_id, 11, 3, 1, 1)
        self.label_receiver_prot = QtWidgets.QLabel(self.widget)
        self.label_receiver_prot.setObjectName("label_receiver_prot")
        self.gridLayout_3.addWidget(self.label_receiver_prot, 12, 2, 1, 1)
        self.label_ans_origin_host = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_ans_origin_host.setFont(font)
        self.label_ans_origin_host.setObjectName("label_ans_origin_host")
        self.gridLayout_3.addWidget(self.label_ans_origin_host, 17, 2, 1, 1)
        self.label_fw_req_payload = QtWidgets.QLabel(self.widget)
        self.label_fw_req_payload.setObjectName("label_fw_req_payload")
        self.gridLayout_3.addWidget(self.label_fw_req_payload, 16, 2, 1, 1)
        self.label_answer_dequeue_date = QtWidgets.QLabel(self.widget)
        self.label_answer_dequeue_date.setObjectName("label_answer_dequeue_date")
        self.gridLayout_3.addWidget(self.label_answer_dequeue_date, 12, 0, 1, 1)
        self.lineEdit_45_first_attempt_receiver_host = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_45_first_attempt_receiver_host.setObjectName("lineEdit_45_first_attempt_receiver_host")
        self.gridLayout_3.addWidget(self.lineEdit_45_first_attempt_receiver_host, 14, 3, 1, 1)
        self.lineEdit_15_answer_send_date = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_15_answer_send_date.setObjectName("lineEdit_15_answer_send_date")
        self.gridLayout_3.addWidget(self.lineEdit_15_answer_send_date, 14, 1, 1, 1)
        self.lineEdit_48_ans_origin_host = QtWidgets.QLineEdit(self.widget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.lineEdit_48_ans_origin_host.setPalette(palette)
        self.lineEdit_48_ans_origin_host.setObjectName("lineEdit_48_ans_origin_host")
        self.gridLayout_3.addWidget(self.lineEdit_48_ans_origin_host, 17, 3, 1, 1)
        self.label_first_attempt_receiver_host = QtWidgets.QLabel(self.widget)
        self.label_first_attempt_receiver_host.setObjectName("label_first_attempt_receiver_host")
        self.gridLayout_3.addWidget(self.label_first_attempt_receiver_host, 14, 2, 1, 1)
        self.label_sender_host = QtWidgets.QLabel(self.widget)
        self.label_sender_host.setObjectName("label_sender_host")
        self.gridLayout_3.addWidget(self.label_sender_host, 17, 0, 1, 1)
        self.label_actual_receiver_host = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setBold(False)
        font.setWeight(50)
        self.label_actual_receiver_host.setFont(font)
        self.label_actual_receiver_host.setObjectName("label_actual_receiver_host")
        self.gridLayout_3.addWidget(self.label_actual_receiver_host, 15, 2, 1, 1)
        self.lineEdit_16_answer_send_Time = QtWidgets.QLineEdit(self.widget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.lineEdit_16_answer_send_Time.setPalette(palette)
        self.lineEdit_16_answer_send_Time.setObjectName("lineEdit_16_answer_send_Time")
        self.gridLayout_3.addWidget(self.lineEdit_16_answer_send_Time, 15, 1, 1, 1)
        self.lineEdit_17_sender_prot = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_17_sender_prot.setObjectName("lineEdit_17_sender_prot")
        self.gridLayout_3.addWidget(self.lineEdit_17_sender_prot, 16, 1, 1, 1)
        self.lineEdit_47_fw_req_payload = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_47_fw_req_payload.setObjectName("lineEdit_47_fw_req_payload")
        self.gridLayout_3.addWidget(self.lineEdit_47_fw_req_payload, 16, 3, 1, 1)
        self.lineEdit_46_actual_receiver_host = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_46_actual_receiver_host.setObjectName("lineEdit_46_actual_receiver_host")
        self.gridLayout_3.addWidget(self.lineEdit_46_actual_receiver_host, 15, 3, 1, 1)
        self.label_answer_send_Time = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_answer_send_Time.setFont(font)
        self.label_answer_send_Time.setObjectName("label_answer_send_Time")
        self.gridLayout_3.addWidget(self.label_answer_send_Time, 15, 0, 1, 1)
        self.lineEdit_13_answer_dequeue_date = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_13_answer_dequeue_date.setObjectName("lineEdit_13_answer_dequeue_date")
        self.gridLayout_3.addWidget(self.lineEdit_13_answer_dequeue_date, 12, 1, 1, 1)
        self.label_ans_origin_realm = QtWidgets.QLabel(self.widget)
        self.label_ans_origin_realm.setObjectName("label_ans_origin_realm")
        self.gridLayout_3.addWidget(self.label_ans_origin_realm, 18, 2, 1, 1)
        self.lineEdit_14_answer_dequeue_time = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_14_answer_dequeue_time.setObjectName("lineEdit_14_answer_dequeue_time")
        self.gridLayout_3.addWidget(self.lineEdit_14_answer_dequeue_time, 13, 1, 1, 1)
        self.label_answer_dequeue_time = QtWidgets.QLabel(self.widget)
        self.label_answer_dequeue_time.setObjectName("label_answer_dequeue_time")
        self.gridLayout_3.addWidget(self.label_answer_dequeue_time, 13, 0, 1, 1)
        self.label_sender_realm = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.label_sender_realm.setFont(font)
        self.label_sender_realm.setObjectName("label_sender_realm")
        self.gridLayout_3.addWidget(self.label_sender_realm, 18, 0, 1, 1)
        self.lineEdit_43_receiver_prot = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_43_receiver_prot.setObjectName("lineEdit_43_receiver_prot")
        self.gridLayout_3.addWidget(self.lineEdit_43_receiver_prot, 12, 3, 1, 1)
        self.lineEdit_19_sender_realm = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_19_sender_realm.setEnabled(True)
        font = QtGui.QFont()
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.lineEdit_19_sender_realm.setFont(font)
        self.lineEdit_19_sender_realm.setObjectName("lineEdit_19_sender_realm")
        self.gridLayout_3.addWidget(self.lineEdit_19_sender_realm, 18, 1, 1, 1)
        self.label_reroute = QtWidgets.QLabel(self.widget)
        self.label_reroute.setObjectName("label_reroute")
        self.gridLayout_3.addWidget(self.label_reroute, 13, 2, 1, 1)
        self.label_sender_prot = QtWidgets.QLabel(self.widget)
        self.label_sender_prot.setObjectName("label_sender_prot")
        self.gridLayout_3.addWidget(self.label_sender_prot, 16, 0, 1, 1)
        self.lineEdit_49_ans_origin_realm = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_49_ans_origin_realm.setObjectName("lineEdit_49_ans_origin_realm")
        self.gridLayout_3.addWidget(self.lineEdit_49_ans_origin_realm, 18, 3, 1, 1)
        self.lineEdit_18_sender_host = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_18_sender_host.setObjectName("lineEdit_18_sender_host")
        self.gridLayout_3.addWidget(self.lineEdit_18_sender_host, 17, 1, 1, 1)
        self.lineEdit_9_request_send_date = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_9_request_send_date.setObjectName("lineEdit_9_request_send_date")
        self.gridLayout_3.addWidget(self.lineEdit_9_request_send_date, 8, 1, 1, 1)
        self.label_start_time = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_start_time.setFont(font)
        self.label_start_time.setObjectName("label_start_time")
        self.gridLayout_3.addWidget(self.label_start_time, 3, 0, 1, 1)
        self.label_fw_ete_id = QtWidgets.QLabel(self.widget)
        self.label_fw_ete_id.setObjectName("label_fw_ete_id")
        self.gridLayout_3.addWidget(self.label_fw_ete_id, 10, 2, 1, 1)
        self.lineEdit_37_msisdn = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_37_msisdn.setObjectName("lineEdit_37_msisdn")
        self.gridLayout_3.addWidget(self.lineEdit_37_msisdn, 6, 3, 1, 1)
        self.label_request_fwd_time = QtWidgets.QLabel(self.widget)
        self.label_request_fwd_time.setObjectName("label_request_fwd_time")
        self.gridLayout_3.addWidget(self.label_request_fwd_time, 5, 0, 1, 1)
        self.lineEdit_40_local_action = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_40_local_action.setObjectName("lineEdit_40_local_action")
        self.gridLayout_3.addWidget(self.lineEdit_40_local_action, 9, 3, 1, 1)
        self.label_fw_hbh_id = QtWidgets.QLabel(self.widget)
        self.label_fw_hbh_id.setObjectName("label_fw_hbh_id")
        self.gridLayout_3.addWidget(self.label_fw_hbh_id, 11, 2, 1, 1)
        self.lineEdit_4_start_time = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_4_start_time.setBaseSize(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.lineEdit_4_start_time.setPalette(palette)
        self.lineEdit_4_start_time.setObjectName("lineEdit_4_start_time")
        self.gridLayout_3.addWidget(self.lineEdit_4_start_time, 3, 1, 1, 1)
        self.label_vplmn_id = QtWidgets.QLabel(self.widget)
        self.label_vplmn_id.setObjectName("label_vplmn_id")
        self.gridLayout_3.addWidget(self.label_vplmn_id, 7, 2, 1, 1)
        self.label_req_ete_id = QtWidgets.QLabel(self.widget)
        self.label_req_ete_id.setObjectName("label_req_ete_id")
        self.gridLayout_3.addWidget(self.label_req_ete_id, 2, 2, 1, 1)
        self.lineEdit_36_imsi = QtWidgets.QLineEdit(self.widget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.lineEdit_36_imsi.setPalette(palette)
        self.lineEdit_36_imsi.setObjectName("lineEdit_36_imsi")
        self.gridLayout_3.addWidget(self.lineEdit_36_imsi, 5, 3, 1, 1)
        self.lineEdit_8_request_dequeue_time = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_8_request_dequeue_time.setObjectName("lineEdit_8_request_dequeue_time")
        self.gridLayout_3.addWidget(self.lineEdit_8_request_dequeue_time, 7, 1, 1, 1)
        self.label_req_hbh_id = QtWidgets.QLabel(self.widget)
        self.label_req_hbh_id.setObjectName("label_req_hbh_id")
        self.gridLayout_3.addWidget(self.label_req_hbh_id, 3, 2, 1, 1)
        self.lineEdit_3_start_date = QtWidgets.QLineEdit(self.widget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.lineEdit_3_start_date.setPalette(palette)
        self.lineEdit_3_start_date.setObjectName("lineEdit_3_start_date")
        self.gridLayout_3.addWidget(self.lineEdit_3_start_date, 2, 1, 1, 1)
        self.lineEdit_6_rquest_fwd_time = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_6_rquest_fwd_time.setObjectName("lineEdit_6_rquest_fwd_time")
        self.gridLayout_3.addWidget(self.lineEdit_6_rquest_fwd_time, 5, 1, 1, 1)
        self.lineEdit_31_dest_operator = QtWidgets.QLineEdit(self.widget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.lineEdit_31_dest_operator.setPalette(palette)
        self.lineEdit_31_dest_operator.setObjectName("lineEdit_31_dest_operator")
        self.gridLayout_3.addWidget(self.lineEdit_31_dest_operator, 0, 3, 1, 1)
        self.lineEdit_32_req_flag = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_32_req_flag.setObjectName("lineEdit_32_req_flag")
        self.gridLayout_3.addWidget(self.lineEdit_32_req_flag, 1, 3, 1, 1)
        self.label_start_date = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_start_date.setFont(font)
        self.label_start_date.setObjectName("label_start_date")
        self.gridLayout_3.addWidget(self.label_start_date, 2, 0, 1, 1)
        self.label_log_date = QtWidgets.QLabel(self.widget)
        self.label_log_date.setObjectName("label_log_date")
        self.gridLayout_3.addWidget(self.label_log_date, 0, 0, 1, 1)
        self.lineEdit_59_reason = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_59_reason.setObjectName("lineEdit_59_reason")
        self.gridLayout_3.addWidget(self.lineEdit_59_reason, 28, 3, 1, 1)
        self.lineEdit_60_reason_id = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_60_reason_id.setObjectName("lineEdit_60_reason_id")
        self.gridLayout_3.addWidget(self.lineEdit_60_reason_id, 29, 3, 1, 1)
        self.lineEdit_57_fw_ans_exp_rst_code = QtWidgets.QLineEdit(self.widget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.lineEdit_57_fw_ans_exp_rst_code.setPalette(palette)
        self.lineEdit_57_fw_ans_exp_rst_code.setObjectName("lineEdit_57_fw_ans_exp_rst_code")
        self.gridLayout_3.addWidget(self.lineEdit_57_fw_ans_exp_rst_code, 26, 3, 1, 1)
        self.label_request_dequeue_time = QtWidgets.QLabel(self.widget)
        self.label_request_dequeue_time.setObjectName("label_request_dequeue_time")
        self.gridLayout_3.addWidget(self.label_request_dequeue_time, 7, 0, 1, 1)
        self.lineEdit_33_req_ete_id = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_33_req_ete_id.setObjectName("lineEdit_33_req_ete_id")
        self.gridLayout_3.addWidget(self.lineEdit_33_req_ete_id, 2, 3, 1, 1)
        self.lineEdit_5_request_fwd_date = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_5_request_fwd_date.setObjectName("lineEdit_5_request_fwd_date")
        self.gridLayout_3.addWidget(self.lineEdit_5_request_fwd_date, 4, 1, 1, 1)
        self.lineEdit_1_log_date = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_1_log_date.setObjectName("lineEdit_1_log_date")
        self.gridLayout_3.addWidget(self.lineEdit_1_log_date, 0, 1, 1, 1)
        self.label_log_time = QtWidgets.QLabel(self.widget)
        self.label_log_time.setObjectName("label_log_time")
        self.gridLayout_3.addWidget(self.label_log_time, 1, 0, 1, 1)
        self.lineEdit_35_req_payload = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_35_req_payload.setObjectName("lineEdit_35_req_payload")
        self.gridLayout_3.addWidget(self.lineEdit_35_req_payload, 4, 3, 1, 1)
        self.label_msisdn = QtWidgets.QLabel(self.widget)
        self.label_msisdn.setObjectName("label_msisdn")
        self.gridLayout_3.addWidget(self.label_msisdn, 6, 2, 1, 1)
        self.lineEdit_2_log_time = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2_log_time.setObjectName("lineEdit_2_log_time")
        self.gridLayout_3.addWidget(self.lineEdit_2_log_time, 1, 1, 1, 1)
        self.label_req_rules_hit = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_req_rules_hit.setFont(font)
        self.label_req_rules_hit.setObjectName("label_req_rules_hit")
        self.gridLayout_3.addWidget(self.label_req_rules_hit, 8, 2, 1, 1)
        self.label_request_dequeue_date = QtWidgets.QLabel(self.widget)
        self.label_request_dequeue_date.setObjectName("label_request_dequeue_date")
        self.gridLayout_3.addWidget(self.label_request_dequeue_date, 6, 0, 1, 1)
        self.label_req_flag = QtWidgets.QLabel(self.widget)
        self.label_req_flag.setObjectName("label_req_flag")
        self.gridLayout_3.addWidget(self.label_req_flag, 1, 2, 1, 1)
        self.label_req_payload = QtWidgets.QLabel(self.widget)
        self.label_req_payload.setObjectName("label_req_payload")
        self.gridLayout_3.addWidget(self.label_req_payload, 4, 2, 1, 1)
        self.label_request_fwd_date = QtWidgets.QLabel(self.widget)
        self.label_request_fwd_date.setObjectName("label_request_fwd_date")
        self.gridLayout_3.addWidget(self.label_request_fwd_date, 4, 0, 1, 1)
        self.label_imsi = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_imsi.setFont(font)
        self.label_imsi.setObjectName("label_imsi")
        self.gridLayout_3.addWidget(self.label_imsi, 5, 2, 1, 1)
        self.lineEdit_7_request_dequeue_date = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_7_request_dequeue_date.setObjectName("lineEdit_7_request_dequeue_date")
        self.gridLayout_3.addWidget(self.lineEdit_7_request_dequeue_date, 6, 1, 1, 1)
        self.gridLayout_2.addWidget(self.widget, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        Show_TDR.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Show_TDR)
        self.statusbar.setObjectName("statusbar")
        Show_TDR.setStatusBar(self.statusbar)

        self.retranslateUi(Show_TDR)
        QtCore.QMetaObject.connectSlotsByName(Show_TDR)

    def retranslateUi(self, Show_TDR):
        _translate = QtCore.QCoreApplication.translate
        Show_TDR.setWindowTitle(_translate("Show_TDR", "Show_TDR"))
        self.label_ans_experiment_result_code.setText(_translate("Show_TDR", "Ans Experiment Result code"))
        self.label_fw_ans_rst_code.setText(_translate("Show_TDR", "Fw-Ans-RstCode"))
        self.label_ans_result_code.setText(_translate("Show_TDR", "Ans Restult Code"))
        self.label_ans_flag.setText(_translate("Show_TDR", "Ans-Flag"))
        self.label_dest_host.setText(_translate("Show_TDR", "Req-Dest-Host"))
        self.label_request_send_date.setText(_translate("Show_TDR", "Request Send Date"))
        self.label_reason_id.setText(_translate("Show_TDR", "Reason-Id"))
        self.label_ans_payload.setText(_translate("Show_TDR", "Ans-Payload"))
        self.label_session_id.setText(_translate("Show_TDR", "Session Id"))
        self.label_request_source_edge_proxy_IP.setText(_translate("Show_TDR", "ReqSrcEdgeProxyIP"))
        self.label_dest_operator.setText(_translate("Show_TDR", "Req-Dest-Operator"))
        self.label_cmd_code.setText(_translate("Show_TDR", "CmdCode"))
        self.label_request_dest_edge_proxy_IP.setText(_translate("Show_TDR", "Req Dest Edge Proxy IP"))
        self.label_ans_rules_hit.setText(_translate("Show_TDR", "Ans-Rules-Hit"))
        self.label_appl_id.setText(_translate("Show_TDR", "Appl Id"))
        self.label_resent.setText(_translate("Show_TDR", "Resent"))
        self.label_reason.setText(_translate("Show_TDR", "Reason"))
        self.label_origin_host.setText(_translate("Show_TDR", "Req-Origin-Host"))
        self.label_fw_ans_payload.setText(_translate("Show_TDR", "Fw-Ans-Payload"))
        self.label_fw_ans_exp_rst_code.setText(_translate("Show_TDR", "Fw-Ans-ExpRstCode"))
        self.label_request_send_time.setText(_translate("Show_TDR", "Request Send Time"))
        self.label_local_action.setText(_translate("Show_TDR", "Local Action"))
        self.label_answer_rcv_date.setText(_translate("Show_TDR", "Answer Rcv Date"))
        self.label_fw_ans_err_msg.setText(_translate("Show_TDR", "Fw-Ans-ErrMsg"))
        self.label_origin_realm.setText(_translate("Show_TDR", "Req-Origin-Realm"))
        self.label_origin_Operator.setText(_translate("Show_TDR", "Req-Origin-Operator"))
        self.label_dest_realm.setText(_translate("Show_TDR", "Req-Dest-Realm"))
        self.label_answer_rcv_time.setText(_translate("Show_TDR", "Answer Rcv Time"))
        self.label_answer_send_date.setText(_translate("Show_TDR", "Answer Send Date"))
        self.label_receiver_prot.setText(_translate("Show_TDR", "Receiver-Prot."))
        self.label_ans_origin_host.setText(_translate("Show_TDR", "Ans-Origin-Host"))
        self.label_fw_req_payload.setText(_translate("Show_TDR", "Fw-Req-Payload"))
        self.label_answer_dequeue_date.setText(_translate("Show_TDR", "Answer Dequeue Date"))
        self.label_first_attempt_receiver_host.setText(_translate("Show_TDR", "FirstAttemptReceiverhost"))
        self.label_sender_host.setText(_translate("Show_TDR", "Sender-Host"))
        self.label_actual_receiver_host.setText(_translate("Show_TDR", "Actual Receiver host"))
        self.label_answer_send_Time.setText(_translate("Show_TDR", "Answer Send Time"))
        self.label_ans_origin_realm.setText(_translate("Show_TDR", "Ans-Origin-Realm"))
        self.label_answer_dequeue_time.setText(_translate("Show_TDR", "Answer Dequeue Time"))
        self.label_sender_realm.setText(_translate("Show_TDR", "Sender-Realm"))
        self.label_reroute.setText(_translate("Show_TDR", "Reroute"))
        self.label_sender_prot.setText(_translate("Show_TDR", "Sender-Prot."))
        self.label_start_time.setText(_translate("Show_TDR", "<html><head/><body><p><span style=\" font-weight:400;\">Start Time</span></p></body></html>"))
        self.label_fw_ete_id.setText(_translate("Show_TDR", "Fw-EtE-Id"))
        self.label_request_fwd_time.setText(_translate("Show_TDR", "Request Fwd Time"))
        self.label_fw_hbh_id.setText(_translate("Show_TDR", "Fw-HbH-Id"))
        self.label_vplmn_id.setText(_translate("Show_TDR", "VPLMN ID"))
        self.label_req_ete_id.setText(_translate("Show_TDR", "Req-EtE-Id"))
        self.label_req_hbh_id.setText(_translate("Show_TDR", "Req-HbH-Id"))
        self.lineEdit_3_start_date.setToolTip(_translate("Show_TDR", "<html><head/><body><p>fdfd</p></body></html>"))
        self.label_start_date.setText(_translate("Show_TDR", "Start Date"))
        self.label_log_date.setText(_translate("Show_TDR", "Log Date"))
        self.label_request_dequeue_time.setText(_translate("Show_TDR", "Request Dequeue Time"))
        self.label_log_time.setText(_translate("Show_TDR", "Log time"))
        self.label_msisdn.setText(_translate("Show_TDR", "MSISDN"))
        self.label_req_rules_hit.setText(_translate("Show_TDR", "<html><head/><body><p><span style=\" font-weight:600; color:#000000;\">Req Rules Hit</span></p></body></html>"))
        self.label_request_dequeue_date.setText(_translate("Show_TDR", "Request Dequeue Date"))
        self.label_req_flag.setText(_translate("Show_TDR", "Req-flag"))
        self.label_req_payload.setText(_translate("Show_TDR", "Req-Payload"))
        self.label_request_fwd_date.setText(_translate("Show_TDR", "Request Fwd Date"))
        self.label_imsi.setText(_translate("Show_TDR", "IMSI"))

