# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tdr_reader_UI_v3.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Input_TDR(object):
    def setupUi(self, Input_TDR):
        Input_TDR.setObjectName("Input_TDR")
        Input_TDR.resize(1376, 698)
        self.centralwidget = QtWidgets.QWidget(Input_TDR)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.SingleTDR = QtWidgets.QTabWidget(self.centralwidget)
        self.SingleTDR.setObjectName("SingleTDR")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setObjectName("frame")
        self.plainTextEdit_TDR = QtWidgets.QPlainTextEdit(self.frame)
        self.plainTextEdit_TDR.setGeometry(QtCore.QRect(30, 40, 1241, 381))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.plainTextEdit_TDR.setPalette(palette)
        self.plainTextEdit_TDR.setObjectName("plainTextEdit_TDR")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(9, 9, 311, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(570, 480, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.frame, 0, 0, 1, 1)
        self.SingleTDR.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.plainTextEdit_SSHoutput = QtWidgets.QPlainTextEdit(self.tab_2)
        self.plainTextEdit_SSHoutput.setGeometry(QtCore.QRect(420, 412, 911, 191))
        self.plainTextEdit_SSHoutput.setPlainText("")
        self.plainTextEdit_SSHoutput.setObjectName("plainTextEdit_SSHoutput")
        self.tableWidget_filterTable = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_filterTable.setEnabled(True)
        self.tableWidget_filterTable.setGeometry(QtCore.QRect(9, 9, 401, 591))
        self.tableWidget_filterTable.setRowCount(60)
        self.tableWidget_filterTable.setObjectName("tableWidget_filterTable")
        self.tableWidget_filterTable.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_filterTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_filterTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_filterTable.setHorizontalHeaderItem(2, item)
        self.tableWidget_filterTable.horizontalHeader().setMinimumSectionSize(20)
        self.tableWidget_filterTable.verticalHeader().setVisible(False)
        self.tableWidget_filterTable.verticalHeader().setDefaultSectionSize(20)
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(420, 9, 461, 201))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox_chooseServer = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_chooseServer.setEnabled(True)
        self.comboBox_chooseServer.setAcceptDrops(False)
        self.comboBox_chooseServer.setAutoFillBackground(False)
        self.comboBox_chooseServer.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStatesMinorOutlyingIslands))
        self.comboBox_chooseServer.setEditable(False)
        self.comboBox_chooseServer.setCurrentText("")
        self.comboBox_chooseServer.setMinimumContentsLength(0)
        self.comboBox_chooseServer.setIconSize(QtCore.QSize(16, 16))
        self.comboBox_chooseServer.setObjectName("comboBox_chooseServer")
        self.gridLayout.addWidget(self.comboBox_chooseServer, 0, 0, 1, 1)
        self.groupBox_listTDR = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_listTDR.setEnabled(True)
        self.groupBox_listTDR.setFlat(False)
        self.groupBox_listTDR.setCheckable(False)
        self.groupBox_listTDR.setChecked(False)
        self.groupBox_listTDR.setObjectName("groupBox_listTDR")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_listTDR)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.pushButton_list_TDR_today = QtWidgets.QPushButton(self.groupBox_listTDR)
        self.pushButton_list_TDR_today.setEnabled(False)
        self.pushButton_list_TDR_today.setObjectName("pushButton_list_TDR_today")
        self.gridLayout_6.addWidget(self.pushButton_list_TDR_today, 0, 0, 1, 1)
        self.pushButton_list_TDR_Before = QtWidgets.QPushButton(self.groupBox_listTDR)
        self.pushButton_list_TDR_Before.setEnabled(False)
        self.pushButton_list_TDR_Before.setObjectName("pushButton_list_TDR_Before")
        self.gridLayout_6.addWidget(self.pushButton_list_TDR_Before, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_listTDR, 0, 1, 2, 1)
        self.groupBox_commandType = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_commandType.setEnabled(False)
        self.groupBox_commandType.setObjectName("groupBox_commandType")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_commandType)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.radioButton_TDR_Today = QtWidgets.QRadioButton(self.groupBox_commandType)
        self.radioButton_TDR_Today.setObjectName("radioButton_TDR_Today")
        self.gridLayout_11.addWidget(self.radioButton_TDR_Today, 0, 0, 1, 1)
        self.groupBox_todaycommand = QtWidgets.QGroupBox(self.groupBox_commandType)
        self.groupBox_todaycommand.setEnabled(False)
        self.groupBox_todaycommand.setTitle("")
        self.groupBox_todaycommand.setObjectName("groupBox_todaycommand")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_todaycommand)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.checkBox_tail = QtWidgets.QCheckBox(self.groupBox_todaycommand)
        self.checkBox_tail.setEnabled(False)
        self.checkBox_tail.setObjectName("checkBox_tail")
        self.gridLayout_4.addWidget(self.checkBox_tail, 0, 0, 1, 1)
        self.checkBox_cat = QtWidgets.QCheckBox(self.groupBox_todaycommand)
        self.checkBox_cat.setEnabled(False)
        self.checkBox_cat.setObjectName("checkBox_cat")
        self.gridLayout_4.addWidget(self.checkBox_cat, 1, 0, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_todaycommand, 0, 1, 1, 1)
        self.radioButton_TDR_Before = QtWidgets.QRadioButton(self.groupBox_commandType)
        self.radioButton_TDR_Before.setObjectName("radioButton_TDR_Before")
        self.gridLayout_11.addWidget(self.radioButton_TDR_Before, 1, 0, 1, 1)
        self.checkBox_zcat = QtWidgets.QCheckBox(self.groupBox_commandType)
        self.checkBox_zcat.setEnabled(False)
        self.checkBox_zcat.setObjectName("checkBox_zcat")
        self.gridLayout_11.addWidget(self.checkBox_zcat, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_commandType, 1, 0, 1, 1)
        self.lineEdit_filename = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_filename.setEnabled(True)
        self.lineEdit_filename.setObjectName("lineEdit_filename")
        self.gridLayout.addWidget(self.lineEdit_filename, 2, 0, 1, 2)
        self.groupBox_listTDR.raise_()
        self.comboBox_chooseServer.raise_()
        self.groupBox_commandType.raise_()
        self.lineEdit_filename.raise_()
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(887, 10, 441, 201))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_grep = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_grep.setObjectName("groupBox_grep")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_grep)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.checkBox_grep1 = QtWidgets.QCheckBox(self.groupBox_grep)
        self.checkBox_grep1.setObjectName("checkBox_grep1")
        self.gridLayout_7.addWidget(self.checkBox_grep1, 0, 0, 1, 1)
        self.lineEdit_grep1 = QtWidgets.QLineEdit(self.groupBox_grep)
        self.lineEdit_grep1.setEnabled(False)
        self.lineEdit_grep1.setObjectName("lineEdit_grep1")
        self.gridLayout_7.addWidget(self.lineEdit_grep1, 0, 1, 1, 1)
        self.checkBox_grep2 = QtWidgets.QCheckBox(self.groupBox_grep)
        self.checkBox_grep2.setObjectName("checkBox_grep2")
        self.gridLayout_7.addWidget(self.checkBox_grep2, 1, 0, 1, 1)
        self.lineEdit_grep2 = QtWidgets.QLineEdit(self.groupBox_grep)
        self.lineEdit_grep2.setEnabled(False)
        self.lineEdit_grep2.setObjectName("lineEdit_grep2")
        self.gridLayout_7.addWidget(self.lineEdit_grep2, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_grep, 3, 0, 1, 3)
        self.checkBox_AddFilter = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_AddFilter.setChecked(True)
        self.checkBox_AddFilter.setObjectName("checkBox_AddFilter")
        self.gridLayout_2.addWidget(self.checkBox_AddFilter, 0, 0, 1, 1)
        self.checkBox_AddTitle = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_AddTitle.setEnabled(True)
        self.checkBox_AddTitle.setObjectName("checkBox_AddTitle")
        self.gridLayout_2.addWidget(self.checkBox_AddTitle, 1, 0, 1, 1)
        self.groupBox_Sort = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_Sort.setEnabled(False)
        self.groupBox_Sort.setTitle("")
        self.groupBox_Sort.setObjectName("groupBox_Sort")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_Sort)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.radioButton_ToTMPDirectory = QtWidgets.QRadioButton(self.groupBox_Sort)
        self.radioButton_ToTMPDirectory.setChecked(True)
        self.radioButton_ToTMPDirectory.setObjectName("radioButton_ToTMPDirectory")
        self.gridLayout_12.addWidget(self.radioButton_ToTMPDirectory, 0, 0, 1, 1)
        self.radioButton_ToLocalDirectory = QtWidgets.QRadioButton(self.groupBox_Sort)
        self.radioButton_ToLocalDirectory.setObjectName("radioButton_ToLocalDirectory")
        self.gridLayout_12.addWidget(self.radioButton_ToLocalDirectory, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_Sort, 1, 1, 1, 2)
        self.checkBox_AddSort = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_AddSort.setEnabled(True)
        self.checkBox_AddSort.setObjectName("checkBox_AddSort")
        self.gridLayout_2.addWidget(self.checkBox_AddSort, 0, 1, 1, 2)
        self.textEdit_test = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_test.setEnabled(True)
        self.textEdit_test.setGeometry(QtCore.QRect(420, 220, 911, 51))
        self.textEdit_test.setObjectName("textEdit_test")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(420, 340, 441, 56))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.comboBox_chooseServer_2 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_chooseServer_2.setEnabled(True)
        self.comboBox_chooseServer_2.setAcceptDrops(False)
        self.comboBox_chooseServer_2.setAutoFillBackground(False)
        self.comboBox_chooseServer_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStatesMinorOutlyingIslands))
        self.comboBox_chooseServer_2.setEditable(False)
        self.comboBox_chooseServer_2.setCurrentText("")
        self.comboBox_chooseServer_2.setMinimumContentsLength(0)
        self.comboBox_chooseServer_2.setIconSize(QtCore.QSize(16, 16))
        self.comboBox_chooseServer_2.setObjectName("comboBox_chooseServer_2")
        self.gridLayout_5.addWidget(self.comboBox_chooseServer_2, 0, 0, 1, 1)
        self.pushButton_FormCommand = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_FormCommand.setObjectName("pushButton_FormCommand")
        self.gridLayout_5.addWidget(self.pushButton_FormCommand, 0, 1, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_4.setGeometry(QtCore.QRect(870, 340, 461, 61))
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.checkBox_AP_Servers = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_AP_Servers.setObjectName("checkBox_AP_Servers")
        self.gridLayout_8.addWidget(self.checkBox_AP_Servers, 0, 0, 1, 1)
        self.pushButton_multiServer = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_multiServer.setObjectName("pushButton_multiServer")
        self.gridLayout_8.addWidget(self.pushButton_multiServer, 0, 3, 1, 1)
        self.checkBox_NA_Servers = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_NA_Servers.setObjectName("checkBox_NA_Servers")
        self.gridLayout_8.addWidget(self.checkBox_NA_Servers, 0, 2, 1, 1)
        self.checkBox_EU_Servers = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_EU_Servers.setObjectName("checkBox_EU_Servers")
        self.gridLayout_8.addWidget(self.checkBox_EU_Servers, 0, 1, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_5.setGeometry(QtCore.QRect(420, 280, 911, 61))
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.comboBox_realmselection = QtWidgets.QComboBox(self.groupBox_5)
        self.comboBox_realmselection.setObjectName("comboBox_realmselection")
        self.gridLayout_9.addWidget(self.comboBox_realmselection, 0, 1, 1, 1)
        self.comboBox_OpName = QtWidgets.QComboBox(self.groupBox_5)
        self.comboBox_OpName.setEditable(True)
        self.comboBox_OpName.setObjectName("comboBox_OpName")
        self.gridLayout_9.addWidget(self.comboBox_OpName, 0, 0, 1, 1)
        self.SingleTDR.addTab(self.tab_2, "")
        self.gridLayout_10.addWidget(self.SingleTDR, 0, 0, 1, 1)
        Input_TDR.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Input_TDR)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1376, 21))
        self.menubar.setObjectName("menubar")
        Input_TDR.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Input_TDR)
        self.statusbar.setObjectName("statusbar")
        Input_TDR.setStatusBar(self.statusbar)

        self.retranslateUi(Input_TDR)
        self.SingleTDR.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Input_TDR)

    def retranslateUi(self, Input_TDR):
        _translate = QtCore.QCoreApplication.translate
        Input_TDR.setWindowTitle(_translate("Input_TDR", "TDR Reader v3.2.1"))
        self.label.setText(_translate("Input_TDR", "Put Single TDR content into below box"))
        self.pushButton.setText(_translate("Input_TDR", "show"))
        self.SingleTDR.setTabText(self.SingleTDR.indexOf(self.tab), _translate("Input_TDR", "Single TDR"))
        item = self.tableWidget_filterTable.horizontalHeaderItem(0)
        item.setText(_translate("Input_TDR", "Name"))
        item = self.tableWidget_filterTable.horizontalHeaderItem(1)
        item.setText(_translate("Input_TDR", "Filter"))
        item = self.tableWidget_filterTable.horizontalHeaderItem(2)
        item.setText(_translate("Input_TDR", "Code"))
        self.groupBox.setTitle(_translate("Input_TDR", "Select Today TDR or TDR before "))
        self.groupBox_listTDR.setTitle(_translate("Input_TDR", "List TDR file name"))
        self.pushButton_list_TDR_today.setText(_translate("Input_TDR", "List TDR Today"))
        self.pushButton_list_TDR_Before.setText(_translate("Input_TDR", "List TDR Before"))
        self.groupBox_commandType.setTitle(_translate("Input_TDR", "Select Command Type"))
        self.radioButton_TDR_Today.setText(_translate("Input_TDR", "Check TDR Today"))
        self.checkBox_tail.setText(_translate("Input_TDR", "tail -f"))
        self.checkBox_cat.setText(_translate("Input_TDR", "cat"))
        self.radioButton_TDR_Before.setText(_translate("Input_TDR", "Check TDR before"))
        self.checkBox_zcat.setText(_translate("Input_TDR", "zcat"))
        self.lineEdit_filename.setPlaceholderText(_translate("Input_TDR", "Copy TDR file name here"))
        self.groupBox_2.setTitle(_translate("Input_TDR", "Filter Box"))
        self.groupBox_grep.setTitle(_translate("Input_TDR", "grep filter"))
        self.checkBox_grep1.setText(_translate("Input_TDR", "Add grep"))
        self.checkBox_grep2.setText(_translate("Input_TDR", "Add grep"))
        self.checkBox_AddFilter.setText(_translate("Input_TDR", "Add Filter"))
        self.checkBox_AddTitle.setText(_translate("Input_TDR", "Add Title"))
        self.radioButton_ToTMPDirectory.setText(_translate("Input_TDR", "Sort To TMP Directory"))
        self.radioButton_ToLocalDirectory.setText(_translate("Input_TDR", "Sort To Local Directory"))
        self.checkBox_AddSort.setText(_translate("Input_TDR", "Add Sort"))
        self.textEdit_test.setHtml(_translate("Input_TDR", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> </p></body></html>"))
        self.groupBox_3.setTitle(_translate("Input_TDR", "To send command to single server"))
        self.pushButton_FormCommand.setText(_translate("Input_TDR", "Form Command"))
        self.groupBox_4.setTitle(_translate("Input_TDR", "To send command to Region servers"))
        self.checkBox_AP_Servers.setText(_translate("Input_TDR", "AP DSC"))
        self.pushButton_multiServer.setText(_translate("Input_TDR", "Form Command"))
        self.checkBox_NA_Servers.setText(_translate("Input_TDR", "NA DSC"))
        self.checkBox_EU_Servers.setText(_translate("Input_TDR", "EU DSC"))
        self.groupBox_5.setTitle(_translate("Input_TDR", "To check and copy OP/Hub diameter realm"))
        self.SingleTDR.setTabText(self.SingleTDR.indexOf(self.tab_2), _translate("Input_TDR", "Group TDR"))

